<a href="https://colab.research.google.com/github/Machine-Learning-Visao-Computacional-T3/semana-02/blob/main/Modelo_IA_Simples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Importando as bibliotecas

In [ ]:
# separacao dos dados de treino e teste
from sklearn.model_selection import train_test_split

# importando o modelo de ML
from sklearn.tree import DecisionTreeClassifier

# manipulacao de dados
import numpy as np
import pandas as pd

# visualizazao de dados
import matplotlib.pyplot as plt
import seaborn as sns

#dataset (conjuntos de dados)
from sklearn.datasets import load_iris

# métricas de analise do modelo
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Coleta de dados trabalhosa

In [ ]:
iris = load_iris() #importando o dataset
X, y = iris.data, iris.target # separacao do X e y

X_treino, X_teste, y_treino, y_teste = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
iris.data[0:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [ ]:
iris.target[0:10]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [ ]:
X_treino = pd.DataFrame(X_treino)
X_teste = pd.DataFrame(X_teste)
y_treino = pd.DataFrame(y_treino)
y_teste = pd.DataFrame(y_teste)

In [ ]:
feature_columns = ['sepal_length','sepal_width','petal_length','petal_width']
target_columns = ['species']

X_treino.columns = feature_columns
X_teste.columns = feature_columns

y_treino.columns = target_columns
y_teste.columns = target_columns

y_teste

    species
0         1
1         0
2         2
3         1
4         1
5         0
6         1
7         2
8         1
9         1
10        2
11        0
12        0
13        0
14        0
15        1
16        2
17        1
18        1
19        2
20        0
21        2
22        0
23        2
24        2
25        2
26        2
27        2
28        0
29        0

# Coleta de dados simples

In [ ]:
df = sns.load_dataset('iris')

In [ ]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

# Analise dos dados

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

# Treino do modelo

In [ ]:
modelo_final = DecisionTreeClassifier(max_depth=3)
modelo_final.fit(X_treino, y_treino)
print("Modelo treino")

Modelo treino

In [ ]:
y_pred = modelo_final.predict(X_teste)

print(f'acuracia:{accuracy_score(y_teste,y_pred)}')
print(f'\n Matriz de confusao:{confusion_matrix(y_teste,y_pred)}')
print(f'\n Relatório de classificacao:{classification_report(y_teste,y_pred, target_names=iris.target_names)}')

acuracia:1.0

 Matriz de confusao:[[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]

 Relatório de classificacao:              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      1.00      1.00         9
   virginica       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30